name: Hello World Action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "Hello, world!"
    - name: Run a multi-line script
      run: |
        echo "Hello, world!"
        echo "This is a multi-line script."
    - name: Run a script from a file
      run: |
        chmod +x ./scripts/hello.sh
        ./scripts/hello.sh
    - name: Run a script with arguments
      run: |
        chmod +x ./scripts/hello_with_args.sh
        ./scripts/hello_with_args.sh "Hello, world!" "This is a script with arguments."
    - name: Run a script with environment variables
      run: |
        chmod +x ./scripts/hello_with_env.sh
        ./scripts/hello_with_env.sh
      env:
        GREETING: "Hello, world!"
        MESSAGE: "This is a script with environment variables."   